### PR TITLE
added some french translations

### PR DESCRIPTION
**Pull request by VirginieLemaire**
Hi 👋🏼 

I added my contribution to French translation but couldn't do much as it was already quite finished ! 
I just could end the Android translation to 100% (with one translation) and tried to reduce length of the Android (Fastlane) translation that needed editing but it's still too long for the max length.
No way to go under as original text seems too long too 🙈

### CODE REVIEW

**Comment by TheLastProject** [comment]
I guess there's indeed not a lot you can do for French anymore yeah. Perhaps you could leave out some less important things in https://hosted.weblate.org/translate/catima/fastlane/fr/?checksum=506009ec08067528 to get the translation below the max limit like:

1. Remove the URLs
2. Simplify "Make it possible to enable or disable the flashlight while scanning" to something like "Support toggling flashlight"
3. Simplify "Support adding a front and back photo to each card" to something like "Add photos to cards"
4. Simplify "Fix useless whitespace in notes from Fidme import" to something like "Ignore whitespace in Fidme import" or even "Improve Fidme import"
5. Simplify "Fix Floating Action Buttons being behind other UI elements on Android 4" to something like "Fix some button foreground issues on Android 4"
6. Simplify "Fix loyalty card viewer appbar top margin" to something like "Card view layout fixes"

All those should still be correct as to what changed that release. Maybe we can get it below 500 then, would be cool if Fastlane can really be 100% correct for French within the app store limits :)

I also see the "Android (Debug)" component for French hasn't been done yet, see https://hosted.weblate.org/projects/catima/-/fr/. You can press the "+" next to "Android (Debug)" to create that component, it only contains one string.

With those things we could truly hit 100% French completion, maybe worth looking at? :)

Thank you!

**Comment by VirginieLemaire** [comment]
Great ! Thank you very much for those ideas. I'll take a look tomorrow

**Comment by VirginieLemaire** [comment]
I applied your advices and now French translation is totally100% 🎉

**Comment by TheLastProject** [comment]
image

So great to see that checkmark :D

Thanks!

**Pull request merged**
