### PR TITLE
Added translations for kannada

### PR DESCRIPTION
**Pull request by nehareddies**

### CODE REVIEW

**Comment by nehareddies** [comment]
I have added in 25 translations for kannada
Added whatever sounds appropriate...

**Comment by nehareddies** [comment]
would be great if you could add hacktoberfest tag here if translations are good to go

**Comment by TheLastProject** [comment]
Can confirm on https://github.com/CatimaLoyalty/Android/commits?author=nehareddies, thanks :)

**Comment by nehareddies** [comment]
Hey it would be great if you could add hacktoberfest label

**Comment by obfusk** [comment]
@nehareddies this repository has the label, that should be sufficient to make your contribution count for hacktoberfest :)

**Pull request merged**
