### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by StoyanDimitrov**
Add my first entry for Hacktober fest ever.

### CODE REVIEW

**Comment by TheLastProject** [comment]
Thanks! I appreciate how you always kept the Bulgarian translation up-to-date!

Looking at https://github.com/CatimaLoyalty/Android/commits?author=StoyanDimitrov, you seem to have only made one translation during October. I would love to just give this to you as you're always there translating (and I find that awesome!), but I'm supposed to only count contributions during October for Hacktoberfest and I don't want to risk getting this repo marked as spam for rewarding "too little work".

Could you maybe pick up a few Fastlane entries? I know they're mostly changelogs and not as important but that way I can show the Hacktoberfest team definite proof that, yup, you made some real contributions during October :)

**Comment by StoyanDimitrov** [comment]
Will do! Thanks for the tip!

**Comment by StoyanDimitrov** [comment]
I think it suffice for a good contribution.

**Comment by TheLastProject** [comment]
Yeah, definitely agreed. Thank you so much :)

**Pull request merged**
