### PR TITLE
Completed translation to Polish

### PR DESCRIPTION
**Pull request by rudy3333**
The Catima base is now 100% translated to Polish.

### CODE REVIEW

**Comment by rudy3333** [comment]
image

**Comment by rudy3333** [comment]
P.S After I corrected the English version to be more readable, the translation is stuck on 99%... Yikes!

**Comment by rudy3333** [comment]
Note : I fixed the issue, I forgot to uncheck editorial request!

**Comment by TheLastProject** [comment]
Thanks for your help! :)

**Pull request merged**
