### PR TITLE
Additions to Romanian

### PR DESCRIPTION
**Pull request by BootVirtual**
17 total additions
11 New translations
6 Changed translations

I avoided translating some strings due to sounding very much like Google Translate. Others were hard to translate due to needing context... But feel free to tell me if there is something to edit.

### CODE REVIEW

**Comment by TheLastProject** [comment]
Thanks! I'll review this next time Weblate makes a PR to update translations (should be within 24 hours).

> I avoided translating some strings due to sounding very much like Google Translate

I'm not sure I completely understand. Do you mean they use some weird English words that are hard to translate in a "natural" way?

> Others were hard to translate due to needing context...

I understand that, some things can be hard to translate if you don't know where it's shown. if you can link to some specific ones that are hard to translate I could maybe add some screenshots for context to make things easier for future translations :)

**Comment by BootVirtual** [comment]
> I'm not sure I completely understand. Do you mean they use some weird English words that are hard to translate in a "natural" way?

You stated in the rules that you wouldn't like seeing strings translated by Google. I've checked the translations Google provides in order to see how I should phrase the strings. But for some, the Google Translate phrasing/translation is correct. I avoided doing those strings for fear of getting denied for Hacktoberfest. I might look into it again after this PR gets merged. But there are also certain terms that I just cannot translate, such as keyring. A lot of tech-related terms just don't exist in Romanian.

**Comment by TheLastProject** [comment]
Ah, like that.

My main concern is people who just put something in Google Translate and copy it as-is without thinking (had cases like that before sadly), but using Google Translate to help you with some difficult English words is fine.

The important part is to make sure you actually speak the language you're translating to so you know when Google Translate is helpful or when it's completely wrong. The important part is that a random person from Romania understands the Romanian translation so it will help them instead of confuse them so as long as you make sure the translation quality is good it's completely fine to let Google Translate help you with some difficult words :)

**Comment by BootVirtual** [comment]
Alright, thanks for the clarification! I'll try to translate more over the following weeks (if time allows me to)

**Comment by TheLastProject** [comment]
Thank you for all your help and useful notes on Weblate :)

**Pull request merged**
