### PR TITLE
completed most of the Italian remaining entries, added comments on errors

### PR DESCRIPTION
**Pull request by Tizzz-555**
The total percentage was bumped to 95%, the biggest issue I noticed is that a few entries have 500 characters limit, but they cannot really be translated in so few letters, given the source is already more than 500 chars. If there is a way to resolve this issue we would probably be closer to 100%

### CODE REVIEW

**Comment by TheLastProject** [comment]
Thanks, can confirm it: https://github.com/CatimaLoyalty/Android/commits?author=Tizzz-555

I can't really do anything about the 500 character limit sadly. Google enforces that and if I change the old English versions every single person will get a notification :(

**Comment by Tizzz-555** [comment]
I see... Maybe trying to summarize the content in the translation then? I assume the links to the PRs have to be kept in the translation as well, right?

**Comment by TheLastProject** [comment]
I've fine with leaving the links or less important details out. Sometimes you can't fit everything, the more technical parts are good to remove first as those are least useful for most users :)

**Comment by Tizzz-555** [comment]
Allright I will go back to it soon then 😉

**Pull request merged**
