### PR TITLE
added Hindi translation

### PR DESCRIPTION
**Pull request by mohitahlawat2001**

### CODE REVIEW

**Comment by TheLastProject** [comment]
Thanks!

I'm curious about one thing: you translated Catima itself to `कैटीमा`, is it normal in Hindi to translate app names?

I also noticed you translated the full description and then deleted the translation again: https://hosted.weblate.org/translate/catima/fastlane/hi/?checksum=502bfece59e1216b&sort_by=-priority,position#history. Was this deletion by accident?

**Comment by mohitahlawat2001** [comment]
> Thanks!
> 
> I'm curious about one thing: you translated Catima itself to `कैटीमा`, is it normal in Hindi to translate app names?
> 
> I also noticed you translated the full description and then deleted the translation again: https://hosted.weblate.org/translate/catima/fastlane/hi/?checksum=502bfece59e1216b&sort_by=-priority,position#history. Was this deletion by accident?

if viewer reading in Hindi then this read कैटीमा same as Catima, word which have no meaning exist in Hindi are write in this way. 

I deleted because i think because their are some conflict at that time.

**Comment by TheLastProject** [comment]
> if viewer reading in Hindi then this read कैटीमा same as Catima, word which have no meaning exist in Hindi are write in this way.

Ah, I see what you mean, if I look up "Coca Cola" on Wikipedia I see their name is also written in Hindi: https://hi.wikipedia.org/wiki/%E0%A4%95%E0%A5%8B%E0%A4%95%E0%A4%BE_%E0%A4%95%E0%A5%8B%E0%A4%B2%E0%A4%BE.

> I deleted because i think because their are some conflict at that time.

I'm not seeing any conflicts there so I'm a bit confused (there is a conflict in this MR because someone else added their name to the end too, you can use GitHub's "Resolve conflicts" button to fix that)

**Comment by mohitahlawat2001** [comment]
I resolve Conflict you Can Check!  
also please add (Hacktoberfest-accepted) label 🙏🏻

**Comment by TheLastProject** [comment]
But what is up with https://hosted.weblate.org/translate/catima/fastlane/hi/?checksum=502bfece59e1216b ? You wrote it and then deleted it? Can you put that back now if it the translation is correct?

**Comment by mohitahlawat2001** [comment]
I just added you can check now.

**Pull request merged**
