### PR TITLE
Marathi Translations are started

### PR DESCRIPTION
**Pull request by Rohan-GIT109**
This commit is to indicate that Marathi translations are started, Thanks to Hacktoberfest.

### CODE REVIEW

**Comment by Rohan-GIT109** [comment]
25% of translations been done

**Comment by Rohan-GIT109** [comment]
@TheLastProject do we have to keep the app_name as it is? Like Catima can be written in Marathi as कटिमा (Read as Kateemaa in Marathi)

**Comment by TheLastProject** [comment]
Do whatever is most normal in your language. Some languages tend to write brand names in their letters, some don't. I don't speak Marathi so I don't know what's normal there :) Just be consistent :)

**Comment by TheLastProject** [comment]
Hi, Hacktoberfest is over. Do you still want to finish up this MR to be listed in the README? :)

**Comment by Rohan-GIT109** [comment]
@TheLastProject I will finish up by this weekend.

**Comment by Rohan-GIT109** [comment]
I am closing this pull request since the Hacktoberfest is over, done about 33% of translations, since i have a day job, can't focus/give 100% of time, It is so much joy, since i rarely get to interact with my native language. I will continue the translation task side by side at slow pace.

**Comment by TheLastProject** [comment]
I understand, I have a day job too. Take your time :)

**Pull request closed without merging**
