### PR TITLE
Added Portuguese Translations

### PR DESCRIPTION
**Pull request by cnfranco**
Added two translations to Catima Android (Fastlane) (https://hosted.weblate.org/projects/catima/fastlane/pt/). 
All the rules were followed.

catima_portuguese

### CODE REVIEW

**Comment by TheLastProject** [comment]
Hi, thanks!

There are 2 more untranslated Portuguese strings, could you take a look at those too please? https://hosted.weblate.org/search/catima/-/pt/?q=state%3A%3Ctranslated&sort_by=-priority%2Cposition&checksum= :)

**Comment by cnfranco** [comment]
Hello!

The translations are done.

image

**Comment by TheLastProject** [comment]
Thanks!

I realized I made a mistake on Weblate, Google only allows up to 30 characters for https://hosted.weblate.org/translate/catima/fastlane/pt/?checksum=1623401ca21ef4e9, not up to 50. So it is too long for the Google Play Store.

I'm merging this MR as this is my fault and you did your work, but if you do happen to have time at some point to make it fit 30 characters instead of 50 that would be awesome :)

**Comment by cnfranco** [comment]
Sure! I can do it for you :D

**Pull request merged**
