### PR TITLE
first commit to a github open source project

### PR DESCRIPTION
**Pull request by l1i1s7a**
I did one minor italian translation edit to test the workflow while participating in hacktoberfest. I'm not a coder, so I'm still figuring it all out. More translations will be coming soon; hope I can be of help!

### CODE REVIEW

**Comment by TheLastProject** [comment]
Hi, thanks for contributing.

I noticed from your GitHub profile you live in Arizona. Were you born in Italy and moved to Arizona or how do you know Italian?

I'm sorry if it feels overly personal for me to ask, Catima has had a lot of issues in the past with people translating languages they didn't speak that well so I want to ask so I can be sure the translations are of good quality :)

**Comment by l1i1s7a** [comment]
Hi there!

I was born in Germany, lived in Italy for most of my life and have moved to Arizona in April.
I have been working as a translator for over four years, and I actually translate English, German, Italian and French. Hope that provides some reassurance!

I understand where Catima is coming from, I have had to deal with/edit weird translations myself for my previous job and it can be a hassle.

This whole github/open-source thing is new for me, just wanted to give it a shot and see if I could be helpful.

**Comment by TheLastProject** [comment]
Ah cool, thank you for confirming, that is really reassuring. I hope Arizona is treating you well :)

I see so far you only removed 1 incorrect line of text which, while definitely helpful, isn't really what I would consider a significant enough contribution. But if you translate a few more things I will definitely hit merge on this pull request to make your help count :)

**Comment by TheLastProject** [comment]
Thanks for contributing! I'm going to merge this now :)

More translations are always very welcome, but I'm going to limit it to 1 PR here per translator because otherwise it starts feeling cheaty and I don't want to risk the Hacktoberfest team invalidating stuff :)

**Pull request merged**
