### PR TITLE
Completed Catima Korean Translation 

### PR DESCRIPTION
**Pull request by kshjessica**
image

**Hey @TheLastProject 😊**
I've just given the README a little makeover to ensure it reflects the most recent project activity of the Korean translation jobs being finished🥳
I'd love for you to take a look and, if you're happy with the changes, consider merging them into the repository. Your time and consideration are much appreciated. Thanks a bunch! 🚀🙏
Plus, sorry for the weird branch ... there must have been a typo😥

**FOLLOWED ALL THE RULES :**
- [x] Do not translate Catima using Google Translate.
- [x] Try to put some actual effort in your contribution.
- [x] Max 1 translation PR per translator.

### CODE REVIEW

**Comment by TheLastProject** [comment]
Thanks!

I looked at your translations and I have one question:
In Catima Debug you wrote "카디마 디버그", but in permissionReadCardsDescription you wrote "당신의 Catima 카드와 그에 대한 모든 세부 정보, 메모 및 이미지를 읽으세요" (so: Catima is written in latin characters there).

Is this a mistake? I would think normally you would write Catima either in English or in Korean and not mix those, right?

**Comment by kshjessica** [comment]
Ah I understand. I'll change all words of "Catima" in English. Thank you for the review!
Let me know there is anything more to change.
@TheLastProject

**Comment by kshjessica** [comment]
I've changed the words!
All strings and words were checked out again but if there some that I left out, do tell me and I'll fix it right away.
Again, thanks for the review:D
@TheLastProject

**Comment by TheLastProject** [comment]
Looks good from what I can tell, thanks :)

**Pull request merged**
